# prometheus.yml postgresql example config

global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'postgres_exporter'    
    static_configs:
      - targets: ['10.42.25.2:9187'] 